packageExtensions:
  '@strapi/strapi@*':
    peerDependencies:
      react: '^17.0.0 || ^18.0.0'
      react-dom: '^17.0.0 || ^18.0.0'
      react-router-dom: '^5.2.0'
      styled-components: '^5.2.1'
    peerDependenciesMeta:
      '@strapi/plugin-cloud':
        optional: true
      '@strapi/plugin-graphql':
        optional: true
      '@strapi/plugin-i18n':
        optional: true
      '@strapi/plugin-users-permissions':
        optional: true
  '@strapi/admin@*':
    dependencies:
      redux: '^5.0.0'
      reselect: '^4.1.8'
      scheduler: '^0.23.0'
  '@strapi/design-system@*':
    dependencies:
      '@codemirror/state': '^6.4.1'
      '@codemirror/view': '^6.26.0'
      '@radix-ui/react-focus-guards': '^1.0.1'
  'markdown-it@*':
    dependencies:
      punycode: '^2.3.1'
  '@strapi/database@*':
    dependencies:
      #[Pin]: Strapi database provider package
      better-sqlite3: '8.6.0'
